var telemetry = {
    1: {
        data: 'Time',
        hasIcon: false,
        title: 'Time: ',
        hasSlider: false,
        value: '12:03:02',
        tier: 1,
        subTier: 1,
        sub_sub_tier: 1
    },
    2: {
        data: 'Oxygen Pressure',
        hasIcon: true,
        icon: 'res/o2_pressure2.png',
        title: '02pressure: ',
        hasSlider: true,
        min: 750,
        max: 950,
        value: 800,
        unit: 'psia',
        tier: 1,
        subTier: 1,
        subSubTier: 1
    },
    3: {
        data: 'Oxygen Rate',
        hasIcon: true,
        icon: 'res/oxygen_rate.png',
        title: 'Oxygen Rate: ',
        hasSlider: true,
        min: 0.5,
        max: 1,
        value: 0.7,
        unit: 'psi/min',
        tier: 1,
        subTier: 1,
        subSubTier: 1
    },
    4: {
        data: 'Battery Capacity',
        hasIcon: true,
        icon: 'res/battery.png',
        title: 'Time: ',
        hasSlider: true,
        min: 0,
        max: 30,
        value: 15,
        unit: 'amp-hr',
        tier: 1,
        subTier: 1,
        subSubTier: 1
    },
    5: {
        data: 'Amp Indicator',
        hasIcon: false,
        title: 'Amp: ',
        hasSlider: false,
        value: 'High!',
        tier: 1,
        subTier: 1,
        subSubTier: 1
    },
    6: {
        data: 'H20 Gas Pressure',
        hasIcon: true,
        title: 'H20 Gas Pressure: ',
        hasSlider: true,
        min: 14,
        max: 16,
        value: 15,
        unit: 'psia',
        tier: 1,
        subTier: 1,
        subSubTier: 1
    },
    7: {
        data: 'H20 Liquid Pressure',
        hasIcon: false,
        title: 'H20 Liquid Pressure',
        hasSlider: false,
        min: 14,
        max: 16,
        value: 15,
        unit: 'psia',
        tier: 1,
        subTier: 1,
        subSubTier: 1
    },
    8: {
        data: 'Sub Pressure',
        hasIcon: false,
        title: 'Sub Pressure',
        hasSlider: false,
        min: 2,
        max: 4,
        value: 3,
        unit: 'psia',
        tier: 1,
        subTier: 1,
        subSubTier: 1
    },
    9: {
        data: 'Sub Temperature',
        hasIcon: false,
        title: 'Sub Temperature',
        hasSlider: false,
        min: 0,
        max: 150,
        value: 60,
        unit: '°f',
        tier: 1,
        subTier: 1,
        subSubTier: 1
    },
    10: {
        data: 'Fan Tachometer',
        hasIcon: false,
        title: 'Amp: ',
        hasSlider: false,
        min: 10000,
        max: 40000,
        value: 30000,
        unit: '°f',
        tier: 1,
        subTier: 1,
        subSubTier: 1
    }
}
exports.telemetry = telemetry;